dashboard_viejo/urls.py
# /home/praevia/praevia/dashboard/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
#from . import views

app_name = 'dashboard'

urlpatterns = []

fasto/urls.py
from django.urls import path
from fasto import fasto_views
app_name='fasto'
urlpatterns = [
    path('',fasto_views.index,name="index"),
    path('index/',fasto_views.index,name="index"),
    path('index-2/',fasto_views.index_2,name="index-2"),
    path('projects',fasto_views.projects,name="projects"),
    path('contacts',fasto_views.contacts,name="contacts"),
    path('kanban',fasto_views.kanban,name="kanban"),
    path('calendar',fasto_views.calendar,name="calendar"),
    path('messages',fasto_views.messages,name="messages"),

    path('app-profile/',fasto_views.app_profile,name="app-profile"),
    path('post-details/',fasto_views.post_details,name="post-details"),
    path('email-compose/',fasto_views.email_compose,name="email-compose"),
    path('email-inbox/',fasto_views.email_inbox,name="email-inbox"),
    path('email-read/',fasto_views.email_read,name="email-read"),
    path('app-calender/',fasto_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',fasto_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',fasto_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',fasto_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',fasto_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',fasto_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',fasto_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',fasto_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',fasto_views.chart_flot,name="chart-flot"),
    path('chart-morris/',fasto_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',fasto_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',fasto_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',fasto_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',fasto_views.chart_peity,name="chart-peity"),

    path('ui-accordion/',fasto_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',fasto_views.ui_alert,name="ui-alert"),
    path('ui-badge/',fasto_views.ui_badge,name="ui-badge"),
    path('ui-button/',fasto_views.ui_button,name="ui-button"),
    path('ui-modal/',fasto_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',fasto_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',fasto_views.ui_list_group,name="ui-list-group"),
    path('ui-media-object/',fasto_views.ui_media_object,name="ui-media-object"),
    path('ui-card/',fasto_views.ui_card,name="ui-card"),
    path('ui-carousel/',fasto_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',fasto_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',fasto_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',fasto_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',fasto_views.ui_tab,name="ui-tab"),
    path('ui-typography/',fasto_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',fasto_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',fasto_views.ui_grid,name="ui-grid"),
    

    path('uc-select2/',fasto_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',fasto_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',fasto_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',fasto_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',fasto_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',fasto_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',fasto_views.uc_lightgallery,name="uc-lightgallery"),
    path('uc-lightgallery/',fasto_views.uc_lightgallery,name="uc-lightgallery"),
    path('widget-basic/',fasto_views.widget_basic,name="widget-basic"),

    path('form-element/',fasto_views.form_element,name="form-element"),
    path('form-wizard/',fasto_views.form_wizard,name="form-wizard"),
    path('form-editor/',fasto_views.form_editor,name="form-editor"),
    path('form-pickers/',fasto_views.form_pickers,name="form-pickers"),
    path('form-validation/',fasto_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',fasto_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',fasto_views.table_datatable_basic,name="table-datatable-basic"),


    path('page-login/',fasto_views.page_login,name="page-login"),
    path('page-register/',fasto_views.page_register,name="page-register"),
    path('page-forgot-password/',fasto_views.page_forgot_password,name="page-forgot-password"),
    path('page-lock-screen/',fasto_views.page_lock_screen,name="page-lock-screen"),
    path('page-empty/',fasto_views.page_empty,name="page-empty"),
    path('page-error-400/',fasto_views.page_error_400,name="page-error-400"),
    path('page-error-403/',fasto_views.page_error_403,name="page-error-403"),
    path('page-error-404/',fasto_views.page_error_404,name="page-error-404"),
    path('page-error-500/',fasto_views.page_error_500,name="page-error-500"),
    path('page-error-503/',fasto_views.page_error_503,name="page-error-503"),
]

praevia_project/urls.py
# /home/praevia/praevia/praevia_project/urls.py

from django.contrib import admin
from django.urls import path, include
from praevia_app.views_api import RootAPIView
from django.conf import settings
from django.views.generic import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static


admin.site.site_header  =  "Fasto Dashboard"  
admin.site.site_title  =  "Dashboard"
admin.site.index_title  =  "Dashboard"
#handler403 = 'dashboard.views.custom_permission_denied_view'
#handler404 = 'dashboard.views.custom_page_not_found_view'

urlpatterns = [
    # 1) Root URL (“/”)
    path('', include(('praevia_app.urls','praevia_app'), namespace='praevia_app')),

    # 2) Admin site
    path('admin/', admin.site.urls),

    # 3) Built‑in auth views (login, logout, password reset at /accounts/…)
    path('two_fa', include(tf_urls)),  # Include 2FA URLs

    # 4) Your custom user URLs (register, etc.); still lives under /register/, /login/, etc.
    path('users/', include('users.urls', namespace='users')),

    # 5) Custom API Root - now points to your custom APIRootView
    path('praevia/api/', RootAPIView.as_view(), name='api-root'),

    # 6) Dashboard pages under /dashboard/
    path('fasto/',include('fasto.urls', namespace='fasto')),
    #path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # 7) Serve favicon.ico
    path('favicon.ico', RedirectView.as_view(url='/static/ico/favicon_api.ico', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fasto/models.py
from django.db import models

# Create your models here.

fasto/views.py
from django.shortcuts import render

# Create your views here.

templates/fasto/pages/page-empty.html
{% extends 'fasto/elements/layouts/admin.html' %}
{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}

<div class="content-body">
    <!-- row -->
    <div class="container-fluid">
        
    </div>
</div>

{% endblock %}

{% block additional_js %}

{% endblock %}

templates/fasto/pages/page-forgot-password.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	{% load static custom_tags %}
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.description }}" />
	<meta property="og:title" content="{{ dz_array.public.og_title }}" />
	<meta property="og:description" content="{{ dz_array.public.og_description }}" />
	<meta property="og:image" content="{{ dz_array.public.og_image }}" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon  %}" />
    {% for cssurl in dz_array.pagelevel.fasto.fasto_views.css|getdata:request.path %}
    <link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
    {% for cssurl in dz_array.global.css %}
    <link rel="stylesheet" href="{% static cssurl %}">
	{% endfor %}
	
	{% block additional_css %}
	{% endblock %}
	
</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<img src="{% static 'fasto/images/logo-full.png' %}" alt="">
									</div>
                                    <h4 class="text-center mb-4">Forgot Password</h4>
                                    <form action="{% url 'fasto:index' %}">
                                        <div class="form-group">
                                            <label><strong>Email</strong></label>
                                            <input type="email" class="form-control" value="hello@example.com">
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">SUBMIT</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
	{% for jsurl in dz_array.global.js.top %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% for jsurl in dz_array.pagelevel.fasto.fasto_views.js|getdata:request.path %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% for jsurl in dz_array.global.js.bottom %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% block additional_js %}
    {% endblock %}

</body>

</html>

templates/fasto/pages/page-lock-screen.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	{% load static custom_tags %}
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.description }}" />
	<meta property="og:title" content="{{ dz_array.public.og_title }}" />
	<meta property="og:description" content="{{ dz_array.public.og_description }}" />
	<meta property="og:image" content="{{ dz_array.public.og_image }}" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon  %}" />
    {% for cssurl in dz_array.pagelevel.fasto.fasto_views.css|getdata:request.path %}
    <link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
    {% for cssurl in dz_array.global.css %}
    <link rel="stylesheet" href="{% static cssurl %}">
	{% endfor %}
	
	{% block additional_css %}
	{% endblock %}
	
</head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<img src="{% static 'fasto/images/logo-full.png' %}" alt="">
									</div>
                                    <h4 class="text-center mb-4">Account Locked</h4>
                                    <form action="{% url 'fasto:index' %}">
                                        <div class="form-group">
                                            <label><strong>Password</strong></label>
                                            <input type="password" class="form-control" value="Password">
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Unlock</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #/ container -->
    <!-- Common JS -->
	{% for jsurl in dz_array.global.js.top %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% for jsurl in dz_array.pagelevel.fasto.fasto_views.js|getdata:request.path %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% for jsurl in dz_array.global.js.bottom %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% block additional_js %}
    
    {% endblock %}
</body>

</html>

templates/fasto/pages/page-login.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	{% load static custom_tags %}
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.description }}" />
	<meta property="og:title" content="{{ dz_array.public.og_title }}" />
	<meta property="og:description" content="{{ dz_array.public.og_description }}" />
	<meta property="og:image" content="{{ dz_array.public.og_image }}" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon  %}" />
    {% for cssurl in dz_array.pagelevel.fasto.fasto_views.css|getdata:request.path %}
    <link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
    {% for cssurl in dz_array.global.css %}
    <link rel="stylesheet" href="{% static cssurl %}">
	{% endfor %}
	
	{% block additional_css %}
	{% endblock %}
	
</head>
<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<img src="{% static 'fasto/images/logo-full.png' %}" alt="">
									</div>
                                    <h4 class="text-center mb-4">Sign in your account</h4>
                                    <form action="{% url 'fasto:index' %}">
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Email</strong></label>
                                            <input type="email" class="form-control" value="hello@example.com">
                                        </div>
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Password</strong></label>
                                            <input type="password" class="form-control" value="Password">
                                        </div>
                                        <div class="form-row d-flex justify-content-between mt-4 mb-2">
                                            <div class="form-group">
                                               <div class="form-check custom-checkbox ms-1">
													<input type="checkbox" class="form-check-input" id="basic_checkbox_1">
													<label class="form-check-label" for="basic_checkbox_1">Remember my preference</label>
												</div>
                                            </div>
                                            <div class="form-group">
                                                <a href="{% url 'fasto:page-forgot-password' %}">Forgot Password?</a>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Sign Me In</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        <p>Don't have an account? <a class="text-primary" href="{% url 'fasto:page-register' %}">Sign up</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
	{% for jsurl in dz_array.global.js.top %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% for jsurl in dz_array.pagelevel.fasto.fasto_views.js|getdata:request.path %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% for jsurl in dz_array.global.js.bottom %}
    <script src="{% static jsurl %}"></script>
    {% endfor %}
    
    {% block additional_js %}
    {% endblock %}
    

</body>

</html>

templates/fasto/pages/page-register.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	{% load static custom_tags %}
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.description }}" />
	<meta property="og:title" content="{{ dz_array.public.og_title }}" />
	<meta property="og:description" content="{{ dz_array.public.og_description }}" />
	<meta property="og:image" content="{{ dz_array.public.og_image }}" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon  %}" />
    {% for cssurl in dz_array.pagelevel.fasto.fasto_views.css|getdata:request.path %}
    <link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
    {% for cssurl in dz_array.global.css %}
    <link rel="stylesheet" href="{% static cssurl %}">
	{% endfor %}
	
	{% block additional_css %}
	{% endblock %}
	
</head>
<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<img src="{% static 'fasto/images/logo-full.png' %}" alt="">
									</div>
                                    <h4 class="text-center mb-4">Sign up your account</h4>
                                    <form action="{% url 'fasto:index' %}">
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Username</strong></label>
                                            <input type="text" class="form-control" placeholder="username">
                                        </div>
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Email</strong></label>
                                            <input type="email" class="form-control" placeholder="hello@example.com">
                                        </div>
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Password</strong></label>
                                            <input type="password" class="form-control" value="Password">
                                        </div>
                                        <div class="text-center mt-4">
                                            <button type="submit" class="btn btn-primary btn-block">Sign me up</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        <p>Already have an account? <a class="text-primary" href="{% url 'fasto:page-login' %}">Sign in</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
   
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.fasto.fasto_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}

</body>
</html>