dashboard_viejo/urls.py
# /home/praevia/praevia/dashboard/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
#from . import views

app_name = 'dashboard'

urlpatterns = []

fasto/urls.py
from django.urls import path
from fasto import fasto_views
app_name='fasto'
urlpatterns = [
    path('',fasto_views.index,name="index"),
    path('index/',fasto_views.index,name="index"),
    path('index-2/',fasto_views.index_2,name="index-2"),
    path('projects',fasto_views.projects,name="projects"),
    path('contacts',fasto_views.contacts,name="contacts"),
    path('kanban',fasto_views.kanban,name="kanban"),
    path('calendar',fasto_views.calendar,name="calendar"),
    path('messages',fasto_views.messages,name="messages"),

    path('app-profile/',fasto_views.app_profile,name="app-profile"),
    path('post-details/',fasto_views.post_details,name="post-details"),
    path('email-compose/',fasto_views.email_compose,name="email-compose"),
    path('email-inbox/',fasto_views.email_inbox,name="email-inbox"),
    path('email-read/',fasto_views.email_read,name="email-read"),
    path('app-calender/',fasto_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',fasto_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',fasto_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',fasto_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',fasto_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',fasto_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',fasto_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',fasto_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',fasto_views.chart_flot,name="chart-flot"),
    path('chart-morris/',fasto_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',fasto_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',fasto_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',fasto_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',fasto_views.chart_peity,name="chart-peity"),

    path('ui-accordion/',fasto_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',fasto_views.ui_alert,name="ui-alert"),
    path('ui-badge/',fasto_views.ui_badge,name="ui-badge"),
    path('ui-button/',fasto_views.ui_button,name="ui-button"),
    path('ui-modal/',fasto_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',fasto_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',fasto_views.ui_list_group,name="ui-list-group"),
    path('ui-media-object/',fasto_views.ui_media_object,name="ui-media-object"),
    path('ui-card/',fasto_views.ui_card,name="ui-card"),
    path('ui-carousel/',fasto_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',fasto_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',fasto_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',fasto_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',fasto_views.ui_tab,name="ui-tab"),
    path('ui-typography/',fasto_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',fasto_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',fasto_views.ui_grid,name="ui-grid"),
    

    path('uc-select2/',fasto_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',fasto_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',fasto_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',fasto_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',fasto_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',fasto_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',fasto_views.uc_lightgallery,name="uc-lightgallery"),
    path('uc-lightgallery/',fasto_views.uc_lightgallery,name="uc-lightgallery"),
    path('widget-basic/',fasto_views.widget_basic,name="widget-basic"),

    path('form-element/',fasto_views.form_element,name="form-element"),
    path('form-wizard/',fasto_views.form_wizard,name="form-wizard"),
    path('form-editor/',fasto_views.form_editor,name="form-editor"),
    path('form-pickers/',fasto_views.form_pickers,name="form-pickers"),
    path('form-validation/',fasto_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',fasto_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',fasto_views.table_datatable_basic,name="table-datatable-basic"),


    path('page-login/',fasto_views.page_login,name="page-login"),
    path('page-register/',fasto_views.page_register,name="page-register"),
    path('page-forgot-password/',fasto_views.page_forgot_password,name="page-forgot-password"),
    path('page-lock-screen/',fasto_views.page_lock_screen,name="page-lock-screen"),
    path('page-empty/',fasto_views.page_empty,name="page-empty"),
    path('page-error-400/',fasto_views.page_error_400,name="page-error-400"),
    path('page-error-403/',fasto_views.page_error_403,name="page-error-403"),
    path('page-error-404/',fasto_views.page_error_404,name="page-error-404"),
    path('page-error-500/',fasto_views.page_error_500,name="page-error-500"),
    path('page-error-503/',fasto_views.page_error_503,name="page-error-503"),
]

praevia_project/urls.py
# /home/praevia/praevia/praevia_project/urls.py

from django.contrib import admin
from django.urls import path, include
from praevia_app.views_api import RootAPIView
from django.conf import settings
from django.views.generic import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static


admin.site.site_header  =  "Fasto Dashboard"  
admin.site.site_title  =  "Dashboard"
admin.site.index_title  =  "Dashboard"
#handler403 = 'dashboard.views.custom_permission_denied_view'
#handler404 = 'dashboard.views.custom_page_not_found_view'

urlpatterns = [
    # 1) Root URL (“/”)
    path('', include(('praevia_app.urls','praevia_app'), namespace='praevia_app')),

    # 2) Admin site
    path('admin/', admin.site.urls),

    # 3) Built‑in auth views (login, logout, password reset at /accounts/…)
    path('two_fa', include(tf_urls)),  # Include 2FA URLs

    # 4) Your custom user URLs (register, etc.); still lives under /register/, /login/, etc.
    path('users/', include('users.urls', namespace='users')),

    # 5) Custom API Root - now points to your custom APIRootView
    path('praevia/api/', RootAPIView.as_view(), name='api-root'),

    # 6) Dashboard pages under /dashboard/
    path('fasto/',include('fasto.urls', namespace='fasto')),
    #path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # 7) Serve favicon.ico
    path('favicon.ico', RedirectView.as_view(url='/static/ico/favicon_api.ico', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/fasto/apps/shop/ecom-product-grid.html
{% extends 'fasto/elements/layouts/admin.html' %}
{% load static %}
        
{% block additional_css %}
{% endblock %}
        
{% block content %}
<!--**********************************
	Content body start
***********************************-->
<div class="content-body">
	<div class="container-fluid">
		<!-- Add Project -->
		<div class="row page-titles mx-0">
			<div class="col-sm-6 p-md-0">
				<div class="welcome-text">
					<h4>Hi, welcome back!</h4>
					<p class="mb-0">Your business dashboard template</p>
				</div>
			</div>
			<div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="javascript:void(0)">Layout</a></li>
					<li class="breadcrumb-item active"><a href="javascript:void(0)">Blank</a></li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/1.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">Bonorum et Malorum</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star-half-empty"></i></li>
									<li><i class="fa fa-star-half-empty"></i></li>
								</ul>
								<span class="price">$761.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/2.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">Striped Dress</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="price">$159.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/3.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">BBow polka-dot</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="price">$357.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/4.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">Z Product 360</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star-half-empty"></i></li>
									<li><i class="fa fa-star-half-empty"></i></li>
								</ul>
								<span class="price">$654.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/5.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">Chair Grey</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="price">$369.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/6.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">fox sake withe</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="price">$245.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/7.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">Back Bag</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="price">$364.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-body">
						<div class="new-arrival-product">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'fasto/images/product/1.jpg' %}" alt="">
							</div>
							<div class="new-arrival-content text-center mt-3">
								<h4><a href="{% url 'fasto:ecom-product-detail' %}">FLARE DRESS</a></h4>
								<ul class="star-rating">
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star-half-empty"></i></li>
									<li><i class="fa fa-star-half-empty"></i></li>
								</ul>
								<span class="price">$548.00</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--**********************************
	Content body end
***********************************-->
{% endblock %}

templates/fasto/apps/shop/ecom-product-list.html
{% extends 'fasto/elements/layouts/admin.html' %}
{% load static %}
        
{% block additional_css %}
{% endblock %}
        
{% block content %}
<!--**********************************
	Content body start
***********************************-->
<div class="content-body">
	<div class="container-fluid">
		<!-- Add Project -->
		<div class="row page-titles mx-0">
			<div class="col-sm-6 p-md-0">
				<div class="welcome-text">
					<h4>Hi, welcome back!</h4>
					<p class="mb-0">Your business dashboard template</p>
				</div>
			</div>
			<div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="javascript:void(0)">Layout</a></li>
					<li class="breadcrumb-item active"><a href="javascript:void(0)">Blank</a></li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 col-xl-6">
				<div class="card">
					<div class="card-body">
						<div class="row m-b-30">
							<div class="col-md-5 col-xxl-12">
								<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
									<div class="new-arrivals-img-contnent">
										<img class="img-fluid" src="{% static 'fasto/images/product/2.jpg' %}" alt="">
									</div>
								</div>
							</div>
							<div class="col-md-7 col-xxl-12">
								<div class="new-arrival-content position-relative">
									<h4><a href="{% url 'fasto:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
									<div class="comment-review star-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star-half-empty"></i></li>
											<li><i class="fa fa-star-half-empty"></i></li>
										</ul>
										<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
										<p class="price">$320.00</p>
									</div>
									<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
									<p>Product code: <span class="item">0405689</span> </p>
									<p>Brand: <span class="item">Lee</span></p>
									<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12 col-xl-6">
				<div class="card">
					<div class="card-body">
						<div class="row m-b-30">
							<div class="col-md-5 col-xxl-12">
								<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
									<div class="new-arrivals-img-contnent">
										<img class="img-fluid" src="{% static 'fasto/images/product/3.jpg' %}" alt="">
									</div>
								</div>
							</div>
							<div class="col-md-7 col-xxl-12">
								<div class="new-arrival-content position-relative">
									<h4><a href="{% url 'fasto:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
									<div class="comment-review star-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star-half-empty"></i></li>
											<li><i class="fa fa-star-half-empty"></i></li>
										</ul>
										<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
										<p class="price">$325.00</p>
									</div>
									<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
									<p>Product code: <span class="item">0405689</span> </p>
									<p>Brand: <span class="item">Lee</span></p>
									<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>                                           
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12 col-xl-6">
				<div class="card">
					<div class="card-body">
						<div class="row m-b-30">
							<div class="col-md-5 col-xxl-12">
								<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
									<div class="new-arrivals-img-contnent">
										<img class="img-fluid" src="{% static 'fasto/images/product/4.jpg' %}" alt="">
									</div>
								</div>
							</div>
							<div class="col-md-7 col-xxl-12">
								<div class="new-arrival-content position-relative">
									<h4><a href="{% url 'fasto:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
									<div class="comment-review star-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
										</ul>
										<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
										<p class="price">$480.00</p>
									</div>
									<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
									<p>Product code: <span class="item">0405689</span> </p>
									<p>Brand: <span class="item">Lee</span></p>
									<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12 col-xl-6">
				<div class="card">
					<div class="card-body">
						<div class="row m-b-30">
							<div class="col-md-5 col-xxl-12">
								<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
									<div class="new-arrivals-img-contnent">
										<img class="img-fluid" src="{% static 'fasto/images/product/5.jpg' %}" alt="">
									</div>
								</div>
							</div>
							<div class="col-md-7 col-xxl-12">
								<div class="new-arrival-content position-relative">
									<h4><a href="{% url 'fasto:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
									<div class="comment-review star-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
										</ul>
										<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
										<p class="price">$658.00</p>
									</div>
									<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
									<p>Product code: <span class="item">0405689</span> </p>
									<p>Brand: <span class="item">Lee</span></p>
									<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12 col-xl-6">
				<div class="card">
					<div class="card-body">
						<div class="row m-b-30">
							<div class="col-md-5 col-xxl-12">
								<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
									<div class="new-arrivals-img-contnent">
										<img class="img-fluid" src="{% static 'fasto/images/product/6.jpg' %}" alt="">
									</div>
								</div>
							</div>
							<div class="col-md-7 col-xxl-12">
								<div class="new-arrival-content position-relative">
									<h4><a href="{% url 'fasto:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
									<div class="comment-review star-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
										</ul>
										<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
										<p class="price">$280.00</p>
									</div>
									<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
									<p>Product code: <span class="item">0405689</span> </p>
									<p>Brand: <span class="item">Lee</span></p>
									<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>                                            
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12 col-xl-6">
				<div class="card">
					<div class="card-body">
						<div class="row m-b-30">
							<div class="col-md-5 col-xxl-12">
								<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
									<div class="new-arrivals-img-contnent">
										<img class="img-fluid" src="{% static 'fasto/images/product/7.jpg' %}" alt="">
									</div>
								</div>
							</div>
							<div class="col-md-7 col-xxl-12">
								<div class="new-arrival-content position-relative">
									<h4><a href="{% url 'fasto:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
									<div class="comment-review star-rating">
										<ul>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
											<li><i class="fa fa-star"></i></li>
										</ul>
										<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
										<p class="price">$600.00</p>
									</div>
									<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
									<p>Product code: <span class="item">0405689</span> </p>
									<p>Brand: <span class="item">Lee</span></p>
									<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- review -->
			<div class="modal fade" id="reviewModal">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title">Review</h5>
							<button type="button" class="btn-close" data-bs-dismiss="modal"></button>
							</button>
						</div>
						<div class="modal-body">
							<form>
								<div class="text-center mb-4">
									<img class="img-fluid rounded" width="78" src="{% static 'fasto/images/avatar/1.jpg' %}" alt="DexignZone">
								</div>
								<div class="form-group">
									<div class="rating-widget mb-4 text-center">
										<!-- Rating Stars Box -->
										<div class="rating-stars">
											<ul id="stars">
												<li class="star" title="Poor" data-value="1">
													<i class="fa fa-star fa-fw"></i>
												</li>
												<li class="star" title="Fair" data-value="2">
													<i class="fa fa-star fa-fw"></i>
												</li>
												<li class="star" title="Good" data-value="3">
													<i class="fa fa-star fa-fw"></i>
												</li>
												<li class="star" title="Excellent" data-value="4">
													<i class="fa fa-star fa-fw"></i>
												</li>
												<li class="star" title="WOW!!!" data-value="5">
													<i class="fa fa-star fa-fw"></i>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<div class="form-group">
									<textarea class="form-control" placeholder="Comment" rows="5"></textarea>
								</div>
								<button class="btn btn-success btn-block">RATE</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--**********************************
	Content body end
***********************************-->
{% endblock %}